version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: oaklang_postgres_db
    restart: always
    environment:
      POSTGRES_USER: oaklang
      POSTGRES_PASSWORD: oaklang
      POSTGRES_DB: oaklang
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis/redis-stack-server:latest
    container_name: oaklang_redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
