import {
  GitHub,
  GitLab,
  Instagram,
  Linkedin,
  ProductHunt,
  Reddit,
  StackExchange,
  TikTok,
  Twitch,
  Twitter,
  Unsplash,
  WakaTime,
  Wikipedia,
  YCombinator,
  YouTube,
} from './extensions/userInfo';
import { GitHubRevoke, StackExchangeRevoke, TikTokRevoke, TwitchRevoke } from './extensions/revoke';
import {
  LinkedinAccessTokenHandler,
  RedditAccessTokenHandler,
  TikTokAccessTokenHandler,
  TwitterAccessTokenHandler,
  YouTubeAccessTokenHandler,
} from './extensions/token';
import { TikTokAuthorizeUrlBuilder, TwitterAuthorizeUrlBuilder } from './extensions/urlBuilders';
import {
  siGithub,
  siGitlab,
  siInstagram,
  siLinkedin,
  siProducthunt,
  siReddit,
  siStackexchange,
  siTiktok,
  siTwitch,
  siTwitter,
  siUnsplash,
  siWakatime,
  siWikipedia,
  siYcombinator,
  siYoutube,
} from 'simple-icons';

import type { InternalIntegration } from '~/utils/types';

export const integrations: InternalIntegration[] = [
  //{ name: siBitbucket.title, icon: siBitbucket.svg },
  //{ name: 'crates.io' },
  {
    authorizeUrl: 'https://github.com/login/oauth/authorize',
    clientId: 'Iv1.9354d99738134238',
    description: 'Your public GitHub repos and public events are used to build your profile and show your language milestones.',
    extraAppInfo: { appId: '393009' },
    icon: siGithub.svg,
    name: siGithub.title,
    postInstallUrl: 'https://github.com/apps/wonderful-dev/installations/new',
    revokeHandler: GitHubRevoke,
    scopes: {
      default: 'user',
    },
    tokenUrl: 'https://github.com/login/oauth/access_token',
    userInfoHandler: GitHub,
  },
  {
    authorizeUrl: 'https://gitlab.com/oauth/authorize',
    clientId: '4fae7ab51cf04d6ef527dcd85ef7b774a91cb172abd2d9330ec219ca9efb8539',
    description: 'Your public GitLab repos and public events are used to build your profile and show your language milestones.',
    icon: siGitlab.svg,
    name: siGitlab.title,
    revokeUrl: 'https://gitlab.com/oauth/revoke',
    scopes: {
      default: 'read_user read_repository read_api',
    },
    tokenUrl: 'https://gitlab.com/oauth/token',
    userInfoHandler: GitLab,
  },
  //{ name: 'Hacker News', icon: siYcombinator.svg },
  //{ name: siLeetcode.title, icon: siLeetcode.svg },
  //{ name: siNpm.title, icon: siNpm.svg },
  //{ name: siProducthunt.title, icon: siProducthunt.svg },
  //{ name: siPypi.title, icon: siPypi.svg },
  {
    accessTokenHandler: RedditAccessTokenHandler,
    authorizeUrl: 'https://www.reddit.com/api/v1/authorize',
    clientId: '3tWtKxxwwr3no3II8Ucfhw',
    description: 'Your Reddit karma is displayed on your profile.',
    icon: siReddit.svg,
    name: siReddit.title,
    revokeUrl: 'https://www.reddit.com/api/v1/revoke',
    scopes: {
      default: 'identity',
    },
    tokenUrl: 'https://www.reddit.com/api/v1/access_token',
    userInfoHandler: Reddit,
  },
  {
    authorizeUrl: 'https://stackoverflow.com/oauth',
    clientId: '27244',
    description: 'Your StackOverflow questions and answers are displayed on your timeline.',
    icon: siStackexchange.svg,
    name: siStackexchange.title,
    revokeHandler: StackExchangeRevoke,
    scopes: {
      default: 'no_expiry',
    },
    tokenUrl: 'https://stackoverflow.com/oauth/access_token',
    userInfoHandler: StackExchange,
  },
  //{ name: siTopcoder.title, icon: siTopcoder.svg },
  {
    accessTokenHandler: LinkedinAccessTokenHandler,
    authorizeUrl: 'https://www.linkedin.com/oauth/v2/authorization',
    clientId: '77wu3767fltdhf',
    description: 'Your LinkedIn follower count is displayed on your profile.',
    icon: siLinkedin.svg,
    name: siLinkedin.title,
    revokeUrl: 'https://www.linkedin.com/oauth/v2/revoke',
    scopes: {
      default: 'openid profile email r_basicprofile r_1st_connections_size',
    },
    tokenUrl: 'https://www.linkedin.com/oauth/v2/accessToken',
    userInfoHandler: Linkedin,
  },
  {
    accessTokenHandler: TwitterAccessTokenHandler,
    authorizeUrl: 'https://twitter.com/i/oauth2/authorize',
    authorizeUrlBuilder: TwitterAuthorizeUrlBuilder,
    clientId: 'ZXd0NXpCUzl4dGlQTUU3bjllZ3Q6MTpjaQ',
    description: 'Your Twitter follower count is displayed on your profile.',
    icon: siTwitter.svg,
    name: siTwitter.title,
    scopes: {
      default: 'users.read offline.access tweet.read',
    },
    tokenUrl: 'https://api.twitter.com/2/oauth2/token',
    userInfoHandler: Twitter,
  },
  {
    authorizeUrl: 'https://wakatime.com/oauth/authorize',
    clientId: 'oCQfP6NKBztpG41fzvT2KGCl',
    description: 'Your WakaTime languages and total code time are displayed on your profile.',
    icon: siWakatime.svg,
    name: siWakatime.title,
    needsScrapeForUserInfo: true,
    revokeUrl: 'https://wakatime.com/oauth/revoke',
    scopes: {
      default: [
        'read_summaries.categories',
        'read_summaries.dependencies',
        'read_summaries.editors',
        'read_summaries.languages',
        'read_summaries.operating_systems',
      ].join(','),
    },
    tokenUrl: 'https://wakatime.com/oauth/token',
    userInfoHandler: WakaTime,
  },
  //{ name: 'Wellfound', icon: siAngellist.svg },
  //{ name: siYoutube.title, icon: siYoutube.svg },
  {
    authorizeUrl: 'https://id.twitch.tv/oauth2/authorize',
    clientId: '0ew7rcv2veyb1ufo6mlui2xk68zwbx',
    description: 'Your Twitch follower count is displayed on your profile.',
    icon: siTwitch.svg,
    name: siTwitch.title,
    revokeHandler: TwitchRevoke,
    scopes: {
      default: 'channel:read:subscriptions moderator:read:followers',
    },
    tokenUrl: 'https://id.twitch.tv/oauth2/token',
    userInfoHandler: Twitch,
  },
  {
    authorizeUrl: 'https://api.producthunt.com/v2/oauth/authorize',
    clientId: '8OiEzwo6HB3c5yyFQSbTfIBtYhzi17fQKLG2KnHMVns',
    description:
      'Your ProductHunt follower count is displayed on your profile, and your noteworthy launches are displayed on your timeline.',
    icon: siProducthunt.svg,
    name: siProducthunt.title,
    needsScrapeForUserInfo: true,
    scopes: {
      default: 'private public',
    },
    tokenUrl: 'https://api.producthunt.com/v2/oauth/token',
    userInfoHandler: ProductHunt,
  },
  {
    accessTokenHandler: YouTubeAccessTokenHandler,
    authorizeUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
    clientId: '761858231574-sscl99mebd9445pbj8vll3d1teh24tcc.apps.googleusercontent.com',
    description: 'Your YouTube subscriber count is displayed on your profile.',
    icon: siYoutube.svg,
    name: siYoutube.title,
    revokeUrl: 'https://oauth2.googleapis.com/revoke',
    scopes: {
      default:
        'https://www.googleapis.com/auth/youtube.readonly openid email profile https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile',
    },
    tokenUrl: 'https://oauth2.googleapis.com/token',
    userInfoHandler: YouTube,
  },
  {
    authorizeUrl: 'https://unsplash.com/oauth/authorize',
    clientId: '515msnrLgSbS8IEacj-QQQu-GMe3yR8ZBs4_re06t3M',
    description: 'Your Unsplash download count is displayed on your profile.',
    icon: siUnsplash.svg,
    name: siUnsplash.title,
    revokeUrl: 'https://unsplash.com/oauth/revoke',
    scopes: {
      default: 'public',
    },
    tokenUrl: 'https://unsplash.com/oauth/token',
    userInfoHandler: Unsplash,
  },
  {
    authorizeUrl: 'https://api.instagram.com/oauth/authorize',
    clientId: '6453722464729305',
    description: 'Your Instagram follower count is displayed on your profile.',
    icon: siInstagram.svg,
    isAwaitingVerification: true,
    name: siInstagram.title,
    // refreshTokenUrl: 'https://api.instagram.com/oauth/refresh_access_token',
    revokeUrl: '',
    scopes: {
      default: 'user_profile',
    },
    tokenUrl: 'https://api.instagram.com/oauth/access_token',
    userInfoHandler: Instagram,
  },
  {
    accessTokenHandler: TikTokAccessTokenHandler,
    authorizeUrl: 'https://www.tiktok.com/v2/auth/authorize',
    authorizeUrlBuilder: TikTokAuthorizeUrlBuilder,
    clientId: 'awwurdhrog3x87dy',
    description: 'Your TikTok follower count is displayed on your profile.',
    icon: siTiktok.svg,
    name: siTiktok.title,
    revokeHandler: TikTokRevoke,
    revokeUrl: 'https://open.tiktokapis.com/v2/oauth/revoke/',
    scopes: {
      default: 'user.info.basic',
    },
    tokenUrl: 'https://open.tiktokapis.com/v2/oauth/token/',
    userInfoHandler: TikTok,
  },
  /*
  Snapchat doesn't show follower counts, even in their app. There's no reason to support Snapchat at this time.
  {
    authorizeUrl: 'https://accounts.snapchat.com/accounts/oauth2/auth',
    clientId: '',
    description: 'Your Snapchat follower count is displayed on your profile.',
    icon: siSnapchat.svg,
    isAwaitingVerification: true,
    name: siSnapchat.title,
    revokeUrl: 'https://accounts.snapchat.com/accounts/oauth2/revoke',
    scopes: {
      default: ' '.join(['user.display_name', 'user.bitmoji.avatar', 'user.external_id']),
    },
    tokenUrl: 'https://accounts.snapchat.com/accounts/oauth2/token',
  },
  */
  {
    authorizeUrl: '',
    clientId: '',
    description:
      'Your HackerNews karma is displayed on your profile, and your noteworthy HackerNews posts or comments are displayed on your timeline.',
    icon: siYcombinator.svg,
    isManualValidation: true,
    name: 'Hacker News',
    scopes: {
      default: '',
    },
    tokenUrl: '',
    userInfoHandler: YCombinator,
  },
  {
    authorizeUrl: 'https://meta.wikimedia.org/w/rest.php/oauth2/authorize',
    clientId: 'a5d10a5fe16f3c9933b38d98952ba75b',
    description: 'Your Wikipedia edit count is displayed on your profile.',
    icon: siWikipedia.svg,
    name: siWikipedia.title,
    revokeUrl: 'https://meta.wikimedia.org/w/rest.php/oauth2/revoke',
    scopes: {
      default: '',
    },
    tokenUrl: 'https://meta.wikimedia.org/w/rest.php/oauth2/access_token',
    userInfoHandler: Wikipedia,
  },
];
