name: test

on:
  schedule:
    - cron: 0 1 * * *
  push:
    branches: [main, master]
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci

  build:
    runs-on: ubuntu-latest
    needs: [setup]
    env:
      NEXT_PUBLIC_BASE_URL: http://localhost:3000
      DATABASE_URL: file:./dev.db
      JWT_SECRET: 1234
      GITHUB_LOGIN_APP_ID: abc
      GITHUB_LOGIN_SECRET: abc
      INTEGRATION_GITHUB_SECRET: abc
      INTEGRATION_GITHUB_SECRET_KEY: abc
      INTEGRATION_STACK_EXCHANGE_CLIENT_ID: abc
      INTEGRATION_STACK_EXCHANGE_SECRET: abc
      INTEGRATION_STACK_EXCHANGE_SECRET_REQUEST_KEY: abc
      INTEGRATION_GITLAB_SECRET: abc
      ADMIN_IDS: abc
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      - name: build
        # TODO: inject envs, possibly use https://neon.tech/ for a fast ephemeral env
        run: npm run build

  lint:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      - name: lint
        run: npm run lint
